version: '3'
services:
    www:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - memcached
    mysql:
        image: 'mysql/mysql-server:8.0'
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './storage/run-mysql:/run/mysqld'
            - './etc/mysql/my.cnf:/etc/my.cnf'
#            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            - './database/database.sh:/docker-entrypoint-initdb.d/10-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mariadb:
        image: 'mariadb'
        restart: always
#        command: --default-authentication-plugin=mysql_native_password
        ports:
#            - '${FORWARD_MARIADB_PORT:-3307}:3307'
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MARIADB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${MARIADB_DATABASE}'
            MYSQL_USER: '${MARIADB_USERNAME}'
            MYSQL_PASSWORD: '${MARIADB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./etc/mariadb/my.cnf:/etc/my.cnf
            - ./storage/sail-mariadb:/var/lib/mysql
            - ./storage/run-mariadb:/run/mysqld
            - ./storage/init-mariadb:/docker-entrypoint-initdb.d
            - ./storage/logs/slow_queries.log:/var/lib/mysql
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${MARIADB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    rcli:
        image: redis:latest
        links:
            - redis
        command: 'redis-cli -h redis'
        networks:
            - sail
    memcached:
        image: 'memcached:alpine'
        ports:
            - '${FORWARD_MEMCACHED_PORT:-11211}:11211'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    #    sail-nginx:
    #        driver: local
    sail-mariadb:
        driver: local
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
